# Generated by Django 3.2.8 on 2021-10-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=254)),
                ('mobile', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('1', 'Female'), ('1', 'Male'), ('1', 'Other'), ('1', 'Prefer Not to')], max_length=50)),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(default='avatar.png', upload_to='profile_pics/')),
                ('path', models.CharField(choices=[('1', 'AWS-DevOps'), ('2', 'Full Stack'), ('3', 'Data Science'), ('4', 'Cyber security'), ('5', 'Custom')], max_length=50)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
