# Generated by Django 3.2.8 on 2021-10-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dastugo_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other'), ('Prefer Not to', 'Prefer Not to')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='default_avatar.png', upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.CharField(blank=True, default='no number yet', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='path',
            field=models.CharField(choices=[('AWS-DevOps', 'AWS-DevOps'), ('Full Stack', 'Full Stack'), ('Data Science', 'Data Science'), ('Cyber Security', 'Cyber Security'), ('Custom', 'Custom')], max_length=50),
        ),
    ]
